vim.keymap.set('n', '<leader>nt', ':Neotree toggle<cr>', { desc = "Toggles neotree" })
vim.keymap.set('n', '<leader>ng', ':Neogit<cr>', { desc = "Neogit UI" })

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, 			{ desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, 			{ desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, 				{ desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, 			{ desc = 'Telescope help tags' })
vim.keymap.set('n', '<leader>fw', builtin.grep_string, 			{ desc = 'Telescope grep string' })
vim.keymap.set('n', '<leader>fs', builtin.lsp_document_symbols, { desc = 'Telescope LSP symbol picker' })
vim.keymap.set('n', '<leader>fr', builtin.lsp_references,		{ desc = 'Telescope LSP reference picker' })
vim.keymap.set('n', '<leader>f"', builtin.resume, 				{ desc = 'Telescope open last picker' })
vim.keymap.set('n', '<leader>?' , builtin.keymaps, 				{ desc = 'Telescope keymaps' })

-- Trouble
vim.keymap.set('n', '<leader>xx', ':Trouble diagnostics toggle<cr>', { desc = 'Trouble diagnostics toggle' })
vim.keymap.set('n', '<leader>xX', ':Trouble diagnostics toggle filter.buf=0<cr>', { desc = 'Trouble diagnostics toggle current buffer' })

vim.keymap.set('n', '<leader>;', ':noh<cr>', { desc = "Removes highlighting"})
vim.keymap.set('n', '<leader>s', function()
	vim.opt.list = not vim.opt.list:get()
end, { desc = "Toggle whitspaces"})

-- Textobjects
vim.keymap.set({ "x", "o" }, "am", function()
  require "nvim-treesitter-textobjects.select".select_textobject("@function.outer", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "im", function()
  require "nvim-treesitter-textobjects.select".select_textobject("@function.inner", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "ac", function()
  require "nvim-treesitter-textobjects.select".select_textobject("@class.outer", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "ic", function()
  require "nvim-treesitter-textobjects.select".select_textobject("@class.inner", "textobjects")
end)
vim.keymap.set({ "x", "o" }, "as", function()
  require "nvim-treesitter-textobjects.select".select_textobject("@local.scope", "locals")
end)
